### ISSUE TITLE
ModuleNotFoundError: No module named 'paystack.urls' 

### ISSUE THREAD

**Issue by Timtech4u** [gbozee/django-paystack#9]
Hi @gbozee ,

On my deployment enviroment I get *ModuleNotFoundError: No module named 'paystack.urls' * 

However the paystack library has been installed and also in my settings.py file.

**Comment by gbozee** [comment]
how did you specify the dependency in you `requirements.txt`?

**Comment by Timtech4u** [comment]
I installed the package using *pipenv install -e git+https://github.com/gbozee/django-paystack.git@master#egg=paystack*

**Comment by Timtech4u** [comment]
Resolved this,  had to clean up use *pipenv install git+https://github.com/gbozee/django-paystack.git@master#egg=paystack*

I'd like to know if there are other ways this library verifies payment without using Webhooks.

**Comment by oyerohabib** [comment]
@Timtech4u i have tried the exact you did but still get error "no module named paystack.urls"

i have also followed this tutorials but i keep getting the same issue

kingly help me

**Comment by Timtech4u** [comment]
> @Timtech4u i have tried the exact you did but still get error "no module named paystack.urls"
> 
> i have also followed this tutorials but i keep getting the same issue
> 
> kingly help me

hey @oyerohabib , can you confirm if you're using a virtual env?

**Comment by 21toffy** [comment]
Hello @Timtech4u i tried your above solution and i am using a virtual environment but i still get "ModuleNotFoundError: No module named 'paystack.urls'"

**Comment by WillDera** [comment]
Has anyone fixed this issue? I also keep getting the same error. 
@Timtech4u After using pipenv install git+https://github.com/gbozee/django-paystack.git@master#egg=paystack it installs it as a normal python package, but the tutorial created needs you to load paystack in one of the templates, I'd like to know how you used it without the "paystack.urls" link

**Comment by blessedmadukoma** [comment]
Please I tried installing but it is not working. I followed each step, but I get this Module error, no module named 'paystack.urls'. Please help

**Comment by MarkChukwuebuka** [comment]
I got the same error and everything is installed properly and i'm not using a virtual environment

**Comment by aayobam** [comment]
i'm also having the same issue as i speak.
